apiVersion: 1

datasources:
  - name: pganalytics
    type: postgres
    access: proxy
    url: postgres:5432
    database: pganalytics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
    isDefault: true
    editable: true
