apiVersion: 1

datasources:
  - name: PostgreSQL (Main)
    type: postgres
    access: proxy
    url: postgres:5432
    database: pganalytics
    user: postgres
    secureJsonData:
      password: pganalytics
    jsonData:
      sslmode: disable
    isDefault: false
    editable: true

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescale:5432
    database: metrics
    user: postgres
    secureJsonData:
      password: pganalytics
    jsonData:
      sslmode: disable
    isDefault: true
    editable: true
